version: 2
jobs:
  build_and_test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      # restore folders with npm dependencies and Cypress binary
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      # install npm dependencies and Cypress binary
      # if they were cached, this step is super quick
      - run:
          name: Install dependencies
          command: npm ci
      # verify Cypress installation
      - run: npm run cy:verify
      # save npm dependencies and Cypress binary for future runs
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      # start server and then run tests
      - run: npm run start

  deploy:
    machine:
        enabled: true
    # working_directory: ~/circleci-demo-workflows
    environment:
      HEROKU_APP: "floating-cliffs-01750" # define env var $HEROKU_APP
      # HEROKU_API_KEY: ca9d4077-e2d8-4d2f-91e7-00e62f1f006b#
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh # run a script to set up Heroku

      - run:
          command: |
            heroku create
            git push heroku circleci-project-setup:master
    

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:  
          requires: 
            - build_and_test
          filters: 
            branches: 
              only: circleci-project-setup
      